export const questions = [
  {
    question: "What is the correct plural form of 'child'?",
    optionA: "Childs",
    optionB: "Childen",
    optionC: "Children",
    optionD: "Childies",
    answer: "C",
  },
  {
    question: "Choose the synonym for 'happy.'",
    optionA: "Sad",
    optionB: "Joyful",
    optionC: "Angry",
    optionD: "Tired",
    answer: "B",
  },
  {
    question:
      "Identify the subject in the following sentence: 'The cat is sleeping on the windowsill.'",
    optionA: "Cat",
    optionB: "Sleeping",
    optionC: "Windowsill",
    optionD: "The",
    answer: "A",
  },
  {
    question: "In which sentence is the preposition used correctly?",
    optionA: "She is good at playing the piano.",
    optionB: "He is allergic of cats.",
    optionC: "They are waiting since an hour.",
    optionD: "We went for shopping yesterday.",
    answer: "A",
  },
  {
    question: "What is the main idea of the passage?",
    optionA: "The benefits of exercise.",
    optionB: "The history of computers.",
    optionC: "How to cook a delicious meal.",
    optionD: "Different types of flowers.",
    answer: "A",
  },
  {
    question: "Choose the correct sentence:",
    optionA: "We're going to the beach, and then we'll ate lunch.",
    optionB: "We're going to the beach, and then we'll eat lunch.",
    optionC: "We're going to the beach, and then we'll eating lunch.",
    optionD: "We're going to the beach, and then we ate lunch.",
    answer: "B",
  },
  {
    question: "Which sentence is punctuated correctly?",
    optionA: "The concert was amazing!!!.",
    optionB: "I love to read, it helps me relax.",
    optionC: "She said, 'I'll be there by 3:30'.",
    optionD: "Let's go for a walk?!",
    answer: "B",
  },
  {
    question: "Choose the correct homophone for 'their.'",
    optionA: "There",
    optionB: "They're",
    optionC: "Thier",
    optionD: "Thare",
    answer: "A",
  },
  {
    question: "Which sentence uses the past tense?",
    optionA: "She will go to the store tomorrow.",
    optionB: "They are playing soccer in the park.",
    optionC: "He ate dinner an hour ago.",
    optionD: "I am going to the movies tonight.",
    answer: "C",
  },
  {
    question: "What does the idiom 'hit the hay' mean?",
    optionA: "Go to bed",
    optionB: "Plant seeds in the garden",
    optionC: "Play a musical instrument",
    optionD: "Hit something with a hay bale",
    answer: "A",
  },
];
